// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using OpenQA.Selenium.DevTools.V108.SystemInfo;
using OpenQA.Selenium.DevTools.V109.SystemInfo;
using FluentAssertions;

[TestFixture]
public class TestCase2Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
 //   Test case 2
	//1. User enters visma.lv
	//2. User click on "Vakances" button
	//3. User click on "Vērtības" on dropped down window
	//4. There should be information about Visma's worker values
    [Test]
    public void testCase2()
    {
        driver.Navigate().GoToUrl("https://www.visma.lv/");

        driver.FindElement(By.CssSelector("#onetrust-accept-btn-handler")).Click();
        driver.FindElement(By.XPath("//*[@id=\"menuControl\"]")).Click();
        driver.FindElement(By.XPath("//*[@id=\"navigation-primary\"]/ul/li[3]/button")).Click();
        driver.FindElement(By.XPath("//*[@id=\"submenu-1571519\"]/ul/li/ul/li[2]/a")).Click();
        var textMessage = driver.FindElement(By.CssSelector("#vertibas > div > h2"));
        textMessage.Text.Should().Be("Kāds ir Visma darbinieks?");
    }
}
