// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Runtime.Intrinsics.X86;

[TestFixture]
public class TestCase4Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
 //   Test case 4
	//1. User enters visma.lv
	//2. User clicks "Apmācības" at the navigation bar
	//3. User should see available courses
  [Test]
  public void testCase4() {
    driver.Navigate().GoToUrl("https://www.visma.lv/");
    driver.FindElement(By.CssSelector("#onetrust-accept-btn-handler")).Click();
    driver.FindElement(By.CssSelector("#menuControl")).Click();
    driver.FindElement(By.LinkText("Apmācības")).Click();
    driver.FindElement(By.CssSelector(".sticky-container")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".one-column-block__body > h2")).Text, Is.EqualTo("Apmācību saraksts"));
  }
}
