// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Runtime.Intrinsics.X86;
using FluentAssertions;

[TestFixture]
public class TestCase5Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
 //   Test case 5
	//1. User enters visma.lv
	//2. User clicks on Blogs
	//3. User should see all blogs and clicks on efektivitate category
	//4. User should see all posts related to efektivitate
    [Test]
    public void testCase5()
    {
        driver.Navigate().GoToUrl("https://www.visma.lv/");
        driver.FindElement(By.CssSelector("#onetrust-accept-btn-handler")).Click();
        driver.FindElement(By.CssSelector("#menuControl")).Click();
        driver.FindElement(By.LinkText("Blogs")).Click();
        driver.FindElement(By.XPath("//*[@id=\"menu-trigger\"]")).Click();
        driver.FindElement(By.XPath("//*[@id=\"mainMenu\"]/ul/li[1]/a")).Click();
        var messageText = driver.FindElement(By.CssSelector(".post-list__item:nth-child(1) .post__category"));
        messageText.Text.Should().Be("Efektivitāte");
    }
}
