// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using FluentAssertions;

[TestFixture]
public class TestCase1Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    //   Test case 1
	//1. User enters visma.lv
	//2. On the main page there should be information block about Visma Labs
    [Test]
    public void testCase1()
    {
        driver.Navigate().GoToUrl("https://www.visma.lv/");
        driver.FindElement(By.CssSelector("#onetrust-accept-btn-handler")).Click();
        var element = driver.FindElement(By.XPath("/html/body/div[2]/div/main/section[3]/aside[2]/div/div/h3"));
        element.Text.Should().Be("Visma\r\nLabs");
    }
}
